create table if not exists filmorate_mpa
(
    mpa_id   int primary key,
    mpa_name varchar(255)
);

create table if not exists filmorate_film
(
    film_id      integer generated by default as identity primary key,
    name         varchar(255),
    description  varchar(200),
    release_date date,
    duration     int,
    mpa_id       int references filmorate_mpa (mpa_id)
);

create table if not exists filmorate_genre
(
    genre_id int primary key,
    name     varchar(255)
);

create table if not exists filmorate_film_genre
(
    film_id  int references filmorate_film (film_id) on delete cascade,
    genre_id int references  filmorate_genre (genre_id) on delete cascade,
    constraint un unique (film_id, genre_id)
);

create table if not exists filmorate_user
(
    user_id  integer generated by default as identity primary key,
    email    varchar(255),
    login    varchar(255),
    name     varchar(255),
    birthday date
);

create table if not exists filmorate_friendship
(
    user_id   int references filmorate_user (user_id) on delete cascade,
    friend_id int references filmorate_user (user_id) on delete cascade,
    constraint un2 unique (user_id, friend_id)
);

create table if not exists filmorate_like
(
    film_id int references filmorate_film (film_id) on delete cascade,
    user_id int references filmorate_user (user_id) on delete cascade,
    constraint un3 unique (film_id, user_id)
);



